### ISSUE TITLE
Secciones del Home

### ISSUE THREAD

**Issue by gtovar** [gtovar/concapital#1]
Analizar las secciones que requerira el sitio y tambien analizar el nombre que van a llevar las secciones. ejemplos

Preguntas Frecuentes
Como funciona
Quien somos
Acerca de nosotros
Conocenos
Que es KonCapital
Quiero Prestar
Quiero invertir
Servicios o Productos
Politicas y Servicios
Privacidad

**Comment by koncapital** [comment]
esto queda  lo revisamos la anterior reunion
