### ISSUE TITLE
Amazon Accesos

### ISSUE THREAD

**Issue by gtovar** [gtovar/concapital#10]
Amazon es un provedor de servicios, vamos a necesitar de sus servicos para almacenar la documentacion de los usuarios, como imagnes o archivos que se le vallan a solicitar.

tambien si se pueden ir regsitrando en amazon, le dejo el link

https://aws.amazon.com/es/s3/

**Comment by koncapital** [comment]
ya me di de alta usuario jose.rivas.vizcarra@gmail.com contraseña pcrm2014

**Comment by gtovar** [comment]
Necesitas terminar el proceso de verficacion, igual si quieres vuelve a iniciar sesion y la pagina te guiara por el proceso

**Comment by koncapital** [comment]
no encuentro como, igual y tambien lo vemos en la siguiente reunion
