### ISSUE TITLE
Pantalla Principal "Quiero prestamo"

### ISSUE THREAD

**Issue by gtovar** [gtovar/concapital#18]
Esta pagina web es una seccion de #25 y tiene varias secciones como: 
- [ ] Como lo solicito #35
- [ ] Requisitos #36
- [ ] Como Pago #37
- [ ] Comisiones #38
- [ ] Cotizador #39
- [ ] Registro #22 
- [ ] Solicitar Prestamo #20 

Esta pagina aparte de quiero prestar que otra informacion necesitan que muestre

**Comment by koncapital** [comment]
todas las secciones son texto informativo, el ultimo de solicitar préstamo ese si es un botón que en caso de estar logeado el usuario lo mande directo a la solicitud de prestamo y en caso de no estar logeado lo mande al acceso de usuario.
