### ISSUE TITLE
Pantalla principal "Quiero Invertir"

### ISSUE THREAD

**Issue by gtovar** [gtovar/concapital#19]
Esta pagina web tiene secciones como:
- [ ] Como Invierto #40 
- [ ] Como creo un portafolio #41
- [ ] Soluciones para empresas #42
- [ ] Comisiones #43
- [ ] Cotizador #24 

1. Ay que tener en cuenta solo las secciones que debe estar para esta primera version.
2. En esta pagina que contenido debe de tener

**Comment by koncapital** [comment]
todo es solo texto informativo y el cotizador pues sería el mismo que se haga para la pagina principal

**Comment by gtovar** [comment]
Ok, al texto informativo que te refieres, ya lo tienen?

**Comment by koncapital** [comment]
algunos textos si otros los estamos redactando.
