### ISSUE TITLE
Solo dos productos

### ISSUE THREAD

**Issue by gtovar** [gtovar/concapital#2]
En las pantallas que vimos en excel ya mencionas  los otros servicios o productos que todavia no existen, seria bueno solo hablar o mostrar los productos que van estar listos para esta primera version. no mencionar otras cosas que todavia no estan hechas.

Que opinas?

**Comment by koncapital** [comment]
Si, de acuerdo lo mas conveniente es solo mostrar los productos que ya van listos en la primera versión.
