### ISSUE TITLE
Pantalla de Inicio del Solicitante

### ISSUE THREAD

**Issue by gtovar** [gtovar/concapital#28]
¿Que cosas vera de entrada el solicitante al iniciar sesion en el sistema?

**Comment by koncapital** [comment]
si ya se registro pero aun no ha terminado la solicitud de crédito debe poder ver directamente la solicitud de crédito, si ya tiene un crédito el también tendrá su estado de cuenta.

**Comment by gtovar** [comment]
"Solicitud de Credito" es la pantalla de "Registrase para Solicitar un Prestamo" #20 

entonces seria uno u otro vdd?
O se le muestra una solicitud de credito o se le muestra su credito, o estado de cuenta es otra funcionalidad

**Comment by koncapital** [comment]
Si, se le mostraría una solicitud de credito si aun no la ha terminado de llenar, si ya tiene un credito entonces se le muestra su estado de cuenta.
