### ISSUE TITLE
Pantalla de Inico del Inversionista

### ISSUE THREAD

**Issue by gtovar** [gtovar/concapital#29]
Cuando un inversionista ingrese al sistema que cosas deberia de ver, ya las tengo anotadas solo falta agregarlas por aqui

**Comment by koncapital** [comment]
cuando el inversionista ingrese debe de observar su estado de cuenta, lo que es una pantalla importante en la que tenemos que trabajar y de ser posible en esa misma pantalla vea algunas opciones para invertir.
