### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by gtovar** [gtovar/concapital#3]
Te gustaria poner una landing page? 

una landing page es donde pones una fecha tentantiva para el lanzamiento de tu sitio web, tambien muestras de que se va tratar de forma muy breve, tambien normalmente se invita al usuario a que nos deje su correo electronico para cuando ya este listo el sitio web, le mandamos una notificacion a su correo invitandolo a visitar el stio.

**Comment by koncapital** [comment]
si me gusta la idea, para que se vayan familiarizando e inscribiendo.

**Comment by gtovar** [comment]
Les gusta este diseño para la cuenta regresiva.

http://demo.bonefishcode.com/bone/file/single.html

**Comment by koncapital** [comment]
si, si nos gusta. nos parece muy bien.

**Comment by gtovar** [comment]
Perfecto, ya tienen alguna redaccion sobre, Ques KonCapital? para que la gente los valla conociendo, al menos unos dos parafos.
