### ISSUE TITLE
Redes Sociales

### ISSUE THREAD

**Issue by gtovar** [gtovar/concapital#4]
Si tienen redes sociales? o en su defecto para yo crearlas y conectarlas, y ustedes pueden ir mientras registrarse en facebook, twitter y google + , para yo mas adelante encontrarlos en estas redes sociales y conectarlos a las redes sociales de KonCapital
Facebook
Twitter
google +

**Comment by koncapital** [comment]
pues si abrí una cuenta de twitter y una pagina de facebook, solo falta google +

**Comment by gtovar** [comment]
Muy bien como los encuentro?

**Comment by koncapital** [comment]
en twitter @koncapital en facebook tambien aparece como koncapital
