### ISSUE TITLE
Logotipo

### ISSUE THREAD

**Issue by gtovar** [gtovar/concapital#6]
Les gustaria que les propusiera algun logotipo?, creo que ya tienen uno la vdd no recuerdo, si ya lo tienen me podrian pasar el archivo original del logotipo.

**Comment by koncapital** [comment]
ya tenemos uno, te lo mando por correo, estamos abiertos sugerencias por si se te ocurre algo que podamos hacer con el logo.

**Comment by koncapital** [comment]
ya te envié el logo por correo.
