### ISSUE TITLE
Traspaso de Propiedad

### ISSUE THREAD

**Issue by gtovar** [gtovar/concapital#8]
Les voy a transferir los proyectos lo que es github y heroku

en github tenemos que hacer privado el repositorio, para que el publico no lo vea y nadie tenga acceso les va pedir tarjeta de credito cuando lo hagan, pero esto si quieren tambien lo hacemos cuando nos juntemos.

**Comment by koncapital** [comment]
si me parece verlo en la siguiente reunión, para que nos expliques como.
