### ISSUE TITLE
darse de alta en playbussines

### ISSUE THREAD

**Issue by koncapital** [gtovar/concapital#9]
recuerda registrarte en playbussines y redactar tu perfil.

**Comment by gtovar** [comment]
Ya quedo solo me falta la del ife es que no me traje mi cartera jejeje

**Comment by koncapital** [comment]
ah también en la misma pagina de playbussines en la opción de MVP en la parte de abajo viene un apartado para especificaciones técnicas, para que cuando tengas oportunidad agregues las especificaciones que consideres importante sobre la plataforma de koncapital.

**Comment by gtovar** [comment]
Ok ya puse los servicos, me faltaria poner que hacen. es que solo dan 1000 caracteres asi que quiero suponer que solo quieren que menciones tecnologias y tecnicas sin su descripcion

**Comment by koncapital** [comment]
dice 1000 caracteres pero te deja poner mucho mas, al menos en las otras opciones tambien dice 1000 caracteres pero no te limita.
